[2022-07-22 01:25:03,897] INFO 130 configuration.py get_training_pipeline_config() Training pipleine config: TrainingPipelineConfig(artifact_dir='D:\\Storessalesproject\\storessales\\artifact')
[2022-07-22 01:25:03,898] INFO 68 configuration.py get_data_ingestion_config() Data Ingestion config: DataIngestionConfig(dataset_download_url='https://drive.google.com/drive/u/0/folders/1jQqqnhgVGqW6qxG1IjAKqArlQP_GER9f/storessalesdata.tgz', tgz_download_dir='D:\\Storessalesproject\\storessales\\artifact\\data_ingestion\\2022-07-22 01-25-03\\tgz_data', raw_data_dir='D:\\Storessalesproject\\storessales\\artifact\\data_ingestion\\2022-07-22 01-25-03\\raw_data', ingested_train_dir='D:\\Storessalesproject\\storessales\\artifact\\data_ingestion\\2022-07-22 01-25-03\\ingested_data\\train', ingested_test_dir='D:\\Storessalesproject\\storessales\\artifact\\data_ingestion\\2022-07-22 01-25-03\\ingested_data\\test')
[2022-07-22 01:25:03,898] INFO 19 data_injection.py __init__() >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2022-07-22 01:25:03,898] ERROR 16 demo.py main() error occured in script: [D:\Storessalesproject\storessales\pipeline\pipeline.py] at line number:[71] error message :[error occured in script: [D:\Storessalesproject\storessales\pipeline\pipeline.py] at line number:[47] error message :[error occured in script: [D:\Storessalesproject\storessales\component\data_injection.py] at line number:[136] error message :[error occured in script: [D:\Storessalesproject\storessales\component\data_injection.py] at line number:[50] error message :[module 'os' has no attribute 'pathexists']]]]
[2022-07-22 01:25:03,900] INFO 141 data_injection.py __del__() >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log completed.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 


